// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Imobiliaria.model
{
    public partial class Agendar
    {
        public int CdAgendar { get; set; }
        public string CdCliente { get; set; }
        public string CdCorretor { get; set; }
        public string CdImovel { get; set; }
        public string DataAgendada { get; set; }
    }
}