// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Imobiliaria.model
{
    public partial class Corretor
    {
        public int CdCorretor { get; set; }
        public string NmCorretor { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string Cpf { get; set; }
        public string DataNascimento { get; set; }
    }
}