// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Imobiliaria.model
{
    public partial class Imoveis
    {
        public int CdImovel { get; set; }
        public string Endereço { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string Cep { get; set; }
        public string Quartos { get; set; }
        public string Banheiros { get; set; }
        public string Garagem { get; set; }
        public string Andares { get; set; }
        public string Tamanho { get; set; }
        public string Tipo { get; set; }
        public string Lavanderia { get; set; }
    }
}